# Generated by cpp11: do not edit by hand

sparse_idxs <- function(is, ps, ns) {
  .Call(`_flotsam_sparse_idxs`, is, ps, ns)
}

spm_times_scalar <- function(ps, xs, ds) {
  .Call(`_flotsam_spm_times_scalar`, ps, xs, ds)
}

nbrhood_triplets <- function(nnt, n_nbrs) {
  .Call(`_flotsam_nbrhood_triplets`, nnt, n_nbrs)
}
