# Generated by cpp11: do not edit by hand

spm_times_scalar <- function(ps, xs, ds) {
  .Call(`_flotsam_spm_times_scalar`, ps, xs, ds)
}

ltsa_triplet_builder_create <- function(value_nnt, value_n_nbrs) {
  .Call(`_flotsam_ltsa_triplet_builder_create`, value_nnt, value_n_nbrs)
}

ltsa_triplet_builder_append <- function(builder_xptr, nni, weights) {
  invisible(.Call(`_flotsam_ltsa_triplet_builder_append`, builder_xptr, nni, weights))
}

ltsa_triplet_builder_finalize <- function(builder_xptr) {
  .Call(`_flotsam_ltsa_triplet_builder_finalize`, builder_xptr)
}

ltsa_local_weights_cpp <- function(x, nni, ndim) {
  .Call(`_flotsam_ltsa_local_weights_cpp`, x, nni, ndim)
}

ltsa_assemble_local_weights <- function(x, value_nnt, value_n_nbrs, ndim, row_major_copy_max_bytes) {
  .Call(`_flotsam_ltsa_assemble_local_weights`, x, value_nnt, value_n_nbrs, ndim, row_major_copy_max_bytes)
}

ltsa_assemble_local_weights_parallel <- function(x, value_nnt, value_n_nbrs, ndim, requested_threads, row_major_copy_max_bytes) {
  .Call(`_flotsam_ltsa_assemble_local_weights_parallel`, x, value_nnt, value_n_nbrs, ndim, requested_threads, row_major_copy_max_bytes)
}
