# Generated by cpp11: do not edit by hand

ltsa_assemble_local_weights_parallel <- function(x, value_nnt, value_n_nbrs, ndim, requested_threads, row_major_copy_max_bytes) {
  .Call(`_flotsam_ltsa_assemble_local_weights_parallel`, x, value_nnt, value_n_nbrs, ndim, requested_threads, row_major_copy_max_bytes)
}

ltsa_assemble_local_weights <- function(x, value_nnt, value_n_nbrs, ndim, row_major_copy_max_bytes) {
  .Call(`_flotsam_ltsa_assemble_local_weights`, x, value_nnt, value_n_nbrs, ndim, row_major_copy_max_bytes)
}

spm_times_scalar <- function(ps, xs, ds) {
  .Call(`_flotsam_spm_times_scalar`, ps, xs, ds)
}
